# Generated by Django 5.2.3 on 2025-08-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
