# Generated by Django 5.2.3 on 2025-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_url_blogpost_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
