# Generated by Django 5.2.3 on 2025-08-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogpost_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='img_url',
            new_name='image',
        ),
    ]
