# Generated by Django 5.2.3 on 2025-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_image_blogpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
